### ISSUE TITLE
Integrate with Github Issues

### ISSUE THREAD

**Issue by pc-alves** [zalando-zmon/zmon-notification-service#28]
Create a notification plugin for Github issues.
This will allow using Github as a repository for low severity alerts that can be analyzed and prioritized during business hours.
An alternative to email notifications that can be easily managed by teams

**Comment by mohabusama** [comment]
Feature to be implemented here: https://github.com/zalando-zmon/zmon-worker/issues/381

**Comment by mohabusama** [comment]
Closing as it needs to be implemented in the worker.
